In [25]:
import numpy as np
import pandas as pd
import sklearn.datasets
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.svm import SVC

In [2]:
load_iris=sklearn.datasets.load_iris()

In [3]:
load_iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [8]:
data_frame=pd.DataFrame(load_iris.data,columns=load_iris.feature_names)
data_frame

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [10]:
data_frame['flower']=load_iris.target

In [11]:
data_frame

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     flower  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [12]:
data_frame.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0       0  
1       0  
2       0  
3       0  
4       0

In [13]:
data_frame.shape

(150, 5)

In [14]:
data_frame.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
flower               0
dtype: int64

In [15]:
#data distribution of target variable

In [16]:
data_frame['flower'].value_counts()

0    50
1    50
2    50
Name: flower, dtype: int64

In [17]:
#SPLIT DATASET INTO DEPENDANT AND INDEPANDANT VARIABLES

In [18]:
X=data_frame.drop('flower',axis='columns')
y=data_frame['flower']

In [19]:
X=np.asarray(X)
y=np.asarray(y)

In [20]:
print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [21]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


## GridSearchCV

In [22]:
#step1 - load svc model
#step 2 - create dictionary for hyperparameters
#step 3 - now do grid searching
#step 4 - fit the data
#step 5 - check for best possible case
#step 6 print for best parameter
#step 7 - print for high score
#step 8 - last step bringing to dataFrame

In [23]:
#step 1 -load svc model

In [45]:
model1=SVC()

In [46]:
model1.fit(X,y)

SVC()

In [50]:
model1.score(X,y)

0.9733333333333334

In [49]:
#step 2 -create dictionary for hyperparameters

In [28]:
parameter={'kernel':['linear','rbf','poly','sigmoid'],
            'C':[1,5,10,20] }

In [29]:
#step 3 - do gridsearching

In [30]:
classifier=GridSearchCV(model,parameter,cv=5)

In [31]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 5, 10, 20],
                         'kernel': ['linear', 'rbf', 'poly', 'sigmoid']})

In [32]:
classifier.cv_results_

{'mean_fit_time': array([0.00469923, 0.00328112, 0.00316424, 0.00529895, 0.        ,
        0.00159831, 0.00320163, 0.00835023, 0.00301428, 0.        ,
        0.00161185, 0.0085371 , 0.001615  , 0.00237966, 0.0032032 ,
        0.00829949]),
 'std_fit_time': array([0.00390985, 0.00401927, 0.00330234, 0.00316622, 0.        ,
        0.00319662, 0.00392118, 0.00061141, 0.00370422, 0.        ,
        0.00322371, 0.00098368, 0.00323   , 0.00298844, 0.00392311,
        0.00081204]),
 'mean_score_time': array([0.00021138, 0.00013108, 0.        , 0.00127325, 0.00318799,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.0002986 , 0.        ,
        0.        ]),
 'std_score_time': array([0.00042276, 0.00026217, 0.        , 0.0025465 , 0.00390449,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.00059719, 0.        ,
        0.        ]),
 'param_C': masked_array(d

In [34]:
classifier.best_params_ #best parameters

{'C': 5, 'kernel': 'rbf'}

In [35]:
classifier.best_score_ #high accuracy

0.9866666666666667

In [36]:
results=pd.DataFrame(classifier.cv_results_)

In [37]:
results.head()

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.004699      0.003910         0.000211        0.000423       1   
1       0.003281      0.004019         0.000131        0.000262       1   
2       0.003164      0.003302         0.000000        0.000000       1   
3       0.005299      0.003166         0.001273        0.002547       1   
4       0.000000      0.000000         0.003188        0.003904       5   

  param_kernel                         params  split0_test_score  \
0       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
1          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
2         poly     {'C': 1, 'kernel': 'poly'}           0.966667   
3      sigmoid  {'C': 1, 'kernel': 'sigmoid'}           0.033333   
4       linear   {'C': 5, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           1.000000           0.966667           0.966667           1.000000   
1           0.966667           0.966667           0.933333           1.000000   
2           1.000000           0.966667           0.966667           1.000000   
3           0.166667           0.000000           0.100000           0.033333   
4           1.000000           0.933333           0.966667           1.000000   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                2  
1         0.966667        0.021082                8  
2         0.980000        0.016330                2  
3         0.066667        0.059628               13  
4         0.980000        0.026667                2

In [38]:
grid_search_results=results[['param_C','param_kernel','mean_test_score']]

In [39]:
grid_search_results

param_C param_kernel  mean_test_score
0        1       linear         0.980000
1        1          rbf         0.966667
2        1         poly         0.980000
3        1      sigmoid         0.066667
4        5       linear         0.980000
5        5          rbf         0.986667
6        5         poly         0.966667
7        5      sigmoid         0.066667
8       10       linear         0.973333
9       10          rbf         0.980000
10      10         poly         0.966667
11      10      sigmoid         0.053333
12      20       linear         0.966667
13      20          rbf         0.980000
14      20         poly         0.966667
15      20      sigmoid         0.040000

In [40]:
model=SVC(kernel='rbf',C=5.0)

In [41]:
model.fit(X,y)

SVC(C=5.0)

In [42]:
model.score(X,y)

0.9866666666666667

## RandomizedSearch CV

In [51]:
#step1 - load svc model
#step 2 - create dictionary for hyperparameters
#step 3 - now do randomized searching
#step 4 - fit the data
#step 5 - check for best possible case
#step 6 print for best parameter
#step 7 - print for high score
#step 8 - last step bringing to dataFrame

In [52]:
model2=SVC()

In [53]:
parameter={'kernel':['linear','rbf','poly','sigmoid'],
           'C':[1,5,10,20]}

In [54]:
classifier1=RandomizedSearchCV(model2,parameter,cv=5)

In [55]:
classifier1.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(),
                   param_distributions={'C': [1, 5, 10, 20],
                                        'kernel': ['linear', 'rbf', 'poly',
                                                   'sigmoid']})

In [57]:
classifier1.cv_results_

{'mean_fit_time': array([0.00320215, 0.00193591, 0.0015285 , 0.00121927, 0.00150285,
        0.00321045, 0.0002739 , 0.00462103, 0.00153866, 0.00267272]),
 'std_fit_time': array([0.00392182, 0.00362291, 0.00183055, 0.00243855, 0.0030057 ,
        0.00393199, 0.00054779, 0.00378784, 0.00052957, 0.00332164]),
 'mean_score_time': array([0.00159855, 0.00100012, 0.00231166, 0.        , 0.        ,
        0.00187826, 0.00311732, 0.0002296 , 0.00111113, 0.00321488]),
 'std_score_time': array([3.19709778e-03, 2.00023651e-03, 2.76781274e-03, 0.00000000e+00,
        0.00000000e+00, 2.88754885e-03, 3.82050813e-03, 4.59194183e-04,
        4.57322882e-05, 3.93748776e-03]),
 'param_kernel': masked_array(data=['linear', 'rbf', 'rbf', 'linear', 'linear', 'rbf',
                    'sigmoid', 'poly', 'linear', 'sigmoid'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'param_C': masked_

In [58]:
results=pd.DataFrame(classifier1.cv_results_)

In [60]:
classifier1.best_params_

{'kernel': 'rbf', 'C': 10}

In [61]:
classifier1.best_score_

0.9800000000000001

In [62]:
results.head()

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0       0.003202      0.003922         0.001599        0.003197       linear   
1       0.001936      0.003623         0.001000        0.002000          rbf   
2       0.001529      0.001831         0.002312        0.002768          rbf   
3       0.001219      0.002439         0.000000        0.000000       linear   
4       0.001503      0.003006         0.000000        0.000000       linear   

  param_C                         params  split0_test_score  \
0      10  {'kernel': 'linear', 'C': 10}           1.000000   
1      10     {'kernel': 'rbf', 'C': 10}           0.966667   
2       1      {'kernel': 'rbf', 'C': 1}           0.966667   
3      20  {'kernel': 'linear', 'C': 20}           1.000000   
4       5   {'kernel': 'linear', 'C': 5}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           1.000000           0.900000           0.966667                1.0   
1           1.000000           0.966667           0.966667                1.0   
2           0.966667           0.966667           0.933333                1.0   
3           1.000000           0.900000           0.933333                1.0   
4           1.000000           0.933333           0.966667                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.973333        0.038873                5  
1         0.980000        0.016330                1  
2         0.966667        0.021082                6  
3         0.966667        0.042164                6  
4         0.980000        0.026667                1

In [63]:
randomized_search_result=results[['param_C','param_kernel','mean_test_score']]

In [64]:
randomized_search_result

param_C param_kernel  mean_test_score
0      10       linear         0.973333
1      10          rbf         0.980000
2       1          rbf         0.966667
3      20       linear         0.966667
4       5       linear         0.980000
5      20          rbf         0.980000
6      10      sigmoid         0.053333
7      20         poly         0.966667
8       1       linear         0.980000
9       5      sigmoid         0.066667

In [65]:
model3=SVC(kernel='rbf',C=10.0)

In [66]:
model3.fit(X,y)

SVC(C=10.0)

In [67]:
model3.score(X,y)

0.9866666666666667